[build]
  command = """
    npm install --global pnpm
    pnpm install --store=node_modules/.pnpm-store
    pnpm build
    """
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--version"
  PYTHON_VERSION = "3.8"